
cc_library(
    name = "XMLPlusPlus",
    visibility = ["//visibility:public"],
    hdrs = [
            "PrintXml.h",
            "CatchConvertError.h",
        ],
    srcs = [
        "CatchConvert.cpp",
    ],
)
