
cc_library(
    name = "XMLPlusPlus",
    visibility = ["//visibility:public"],
    hdrs = [
            "CatchConvertError.h",
            "CatchConvertError.cpp",
            "PrintXML.cpp",
        ],
)
