cc_library(

    name = "other",

    deps = [
        "libstdc++.so.6",
        "libz.so.1", 
        "libwind.so.0",
        "libtasn1.so.6",  
        "libssl.so.1.0.0",
        "libsqlite3.so.0",
        "libsigc-2.0.so.0",
        "libsasl2.so.2",
        "librtmp.so.0",
        "libroken.so.18",
        "libresolv.so.2",
        "libpthread.so.0",
        "libpcre.so.3",
        "libp11-kit.so.0",
        "liblzma.so.5", 
        "libm.so.6",
        "libldap_r-2.4.so.2",
        "liblber-2.4.so.2",
        "libkrb5support.so.0",
        "libkrb5.so.3",
        "libkrb5.so.26",
        "libkeyutils.so.1",     
    ]
)

