cc_library(

    name = "other",

    deps = [
        "libstdc++.so.6",
        "libz.so.1", 
        "libwind.so.0",
        "libtasn1.so.6",  
        "libssl.so.1.0.0",
        "libsqlite3.so.0",
    ]
)

