cc_library(

    name = "other",

    deps = [
        "libstdc++.so.6",
        "libz.so.1", 
        "libwind.so.0",
        "libtasn1.so.6",  
        "libssl.so.1.0.0",
        "libsqlite3.so.0",
        "libsigc-2.0.so.0",
        "libsasl2.so.2",
        "librtmp.so.0",
        "libroken.so.18",
    ]
)

